### ISSUE TITLE
C# conversion 

### ISSUE THREAD

**Issue by Crystalwarrior** [matt-kimball/godot-mrpas#2]
The godot implementation is cool and I'm using it right now, but I'm wondering if the algorithm can be made faster if written in c#?

**Comment by matt-kimball** [comment]
Yes, probably it would be faster.  I wrote it with the intention of supporting web exports, though, which does not support C# as of Godot 4.2.

I think it would be nice for someone to make a C# version available, but that is outside the scope of this project.
